name: Build and Deploy Voting App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Voting App
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Deploy the application (example step)
        run: |
          echo "Deploying the application..."
          # Ajoute tes commandes de déploiement ici (par exemple vers un serveur ou un cloud)
